services:
  - type: web
    name: brain-tumor-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      mkdir -p model
      curl -L https://github.com/kaanchiiii/Brain-Tumor-Detection-Model/releases/download/v1.0/model.h5 -o model/model.h5
      python app.py
